### PR TITLE
add notes field

### PR DESCRIPTION
**Pull request by justeph**
some vouchers have a pin code that is required to use them in the
corresponding stores, so add an optionnal detail field to be able to
add a pin code

Signed-off-by: Julien STEPHAN <stephan-julien@laposte.net>

### CODE REVIEW

**Comment by justeph** [comment]
Hi,
I tested this merge request only on android.
It partially fix https://github.com/tim-smart/vouchervault/issues/10

**Comment by tim-smart** [comment]
Thanks! Looks good.

I think we should just add a notes field, instead of a field specifically for pin codes.

You are almost there with this change. We would just need to rename the field to "notes", and in the form use a text input that supports adding new lines.

We would only show the notes in the pop-up dialog, not the list view.

Let me know if you want to try this, otherwise I can take over.

**Comment by justeph** [comment]
Hi Tim,
Understood, I will push a new merge request. 
Best
Julien

Le 22 janvier 2022 00:35:07 GMT+01:00, Tim ***@***.***> a écrit :

**Comment by justeph** [comment]
Hi Tim,
I pushed a new commit to add note support.
I kept my commit adding the pin code, because I find it's more usable to have a dedicated field for it, using numeric keypad and a nice lock icon ;) I modified it, to not display the pin code in the list view as you suggested. 
Let me know if you want me to do any modification
Julien

**Comment by tim-smart** [comment]
Thanks! I have just taken the notes commit at this time.

I'm still thinking about the pin code field - feel free to open another pull request if you want to discuss it further.

**Pull request closed without merging**
